resources:
  repositories:
  - repository: ci-wex-build
    type: github
    endpoint: ci-wex-build
    name: wincomplm/ci-wex-build

pool:
  vmImage: windows-latest

variables:
- group: EDK Build Settings

jobs:
- job: BuildExtension
  displayName: Build Extension

  steps:
  - checkout: self
  - checkout: ci-wex-build

  - task: PowerShell@2  
    displayName: 'Getting Wex file'
    inputs:
      targetType: inline
      script: |
        $dir = '$(Build.SourcesDirectory)/edk-examples/'
        write-host "dir '$dir'"
        $file = Get-ChildItem $dir -Recurse | where {$_.extension -in @(".wex")} | % { $_.FullName }
        Write-Host "##vso[task.setvariable variable=buildId;]$file"
        $(buildId) = $file
        write-host "env $env:buildId"