resources:
  repositories:
  - repository: ci-wex-build
    type: github
    endpoint: ci-wex-build
    name: wincomplm/ci-wex-build

pool:
  vmImage: windows-latest

variables:
- group: EDK Build Settings

jobs:
- job: BuildExtension
  displayName: Build Extension

  steps:
  - checkout: self
  - checkout: ci-wex-build

  - task: JavaToolInstaller@0
    displayName: 'Use Java 11'
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'wincomplm-products'
  - task: PowerShell@2
    displayName: 'Maven setup'
    inputs:
      targetType: 'inline'
      script: |
        $pwd = '$(support-wex-pwd)'
        $userid = '$(support-wex-userid)'
        ((Get-Content -path $(Build.SourcesDirectory)/ci-wex-build/build/settings.xml -Raw) -replace [regex]::escape('[password]'),$pwd) | Set-Content -Path $(Build.SourcesDirectory)/ci-wex-build/build/settings.xml
        ((Get-Content -path $(Build.SourcesDirectory)/ci-wex-build/build/settings.xml -Raw) -replace [regex]::escape('[userid]'),$userid) | Set-Content -Path $(Build.SourcesDirectory)/ci-wex-build/build/settings.xml
        Copy-Item $(Build.SourcesDirectory)/ci-wex-build/build/settings.xml -Destination ~/.m2
  - task: Maven@3
    displayName: 'Build $(wcversion)'
    inputs:
      mavenPomFile: '$(Build.SourcesDirectory)/edk-examples/$(artifactId)/pom.xml'
      mavenOptions: '-Xmx3072m'
      options: '-P $(wcversion) -Dcve.check.skip=false -Djar.sign=true -Dwex.sign=true -Dwex.junit.exclude=none'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      goals: 'install'
  - task: PowerShell@2
    displayName: 'Getting Wex file'
    inputs:
      targetType: inline
      script: |
        $dir = $(system.defaultworkingdirectory)\
        $file = Get-ChildItem $dir -Recurse | where {$_.extension -in @(".wex")} | % { $_.FullName }
        Copy-Item $file -Destination '$(build.artifactstagingdirectory)/'

  - task: PowerShell@2
    displayName: 'Deploy Single WEX on Auto Test Server'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/ci-wex-build/build/deployToWindchill.ps1'
      arguments: '-user $(wcadmin) -pass $(wcpassword) -wcserver "https://wex-auto-test.wincom-cloud.net/Windchill" -file $(build.artifactstagingdirectory)/$(buildId)'
  - task: PowerShell@2
    displayName: 'Execute jUnit tests on Auto Test Server'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/ci-wex-build/build/runJunitTests.ps1'
      arguments: -user $(wcadmin) -pass $(wcpassword) -wcserver "https://wex-auto-test.wincom-cloud.net/Windchill" -junitpath "wex/example/ui"
  
  - task: DeleteFiles@1
    inputs:
      SourceFolder: '$(build.artifactstagingdirectory)'
      Contents: '**/*.wex'

  - task: CopyFiles@2
    displayName: 'Copy Files Staging'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.security.pdf'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PowerShell@2
    displayName: 'Upload security report to teams'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/ci-wex-build/build/uploadToSharePointFilePath.ps1'
      arguments: '-SPVersion "Online" -SPUsername $(sp.user) -SPPassword $(sp.pwd) -SPURL https://wincomconsulting.sharepoint.com/sites/EDK-External -SPFolder /Documentos%20compartidos%2FReports -Folder $(build.artifactstagingdirectory)'      
      