# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  displayName: 'Upload to teams'
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/ci-wex-build/build/uploadToSharePointFilePath.ps1'
    arguments: '-SPVersion "Online" -SPUsername $(sp.user) -SPPassword $(sp.pwd) -SPURL https://wincomconsulting.sharepoint.com/sites/WexProducts -SPFolder /Documentos%20compartidos/$(teams-folder)/Latest -Folder $(build.artifactstagingdirectory)/wex'      
      
