resources:
  repositories:
  - repository: ci-wex-build
    type: github
    endpoint: ci-wex-build
    name: wincomplm/ci-wex-build

pool:
  vmImage: windows-latest

variables:
- group: EDK Build Settings

jobs:
- job: BuildExtension
  displayName: Build Extension

  steps:
  - checkout: self
  - checkout: ci-wex-build

  - task: PowerShell@2
    displayName: 'Getting Wex file'
    inputs:
      targetType: inline
      script: |
        $file = "pepito"
        Write-Host "##vso[task.setvariable variable=buildId;]$file"
        [string] $wexId= $Env:buildId
        Write-Host "The buildId environment variable value is '$wexId'." 
        write-host "env $Env:buildId"